import type { NextPage } from "next";
import Head from "next/head";
import { PageTemplate } from "@/components";
import Styles from "../styles/internals.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTemplate>
        
      </PageTemplate>
    </>
  );
};

export default Home;